### ISSUE TITLE
iSeries (as/400) DB2 - not compatible via pdo_ibm or odbc

### ISSUE THREAD

**Issue by Andrewpk** [edgardmessias/yiidb2#1]
I just wanted to post this as an issue for anyone else looking around for yii -> iSeries db2 connectivity (as/400). This, and many other extensions/plugins for yii and other frameworks to connect to db2 with the ORM are generally built for db2 running on UNIX/Linux/etc - not an IBM iSeries (as/400). I'm almost finished with my work on making this run on an iSeries and I would like to submit it as a pull request if you don't mind the addition.

Thanks,
Andrew

Also, connecting to an iSeries DB2 instance is generally done via ODBC to mitigate licensing costs - just throwing that out there as well.

**Comment by edgardmessias** [comment]
The tests I did and worked well were:

``` php
'connectionString' => 'ibm:DRIVER={IBM DB2 ODBC DRIVER};DATABASE=database;HOSTNAME=hostname;PORT=port;PROTOCOL=TCPIP;',
```

and

``` php
'connectionString' => 'odbc:DRIVER={IBM DB2 ODBC DRIVER};DATABASE=database;HOSTNAME=hostname;PORT=port;PROTOCOL=TCPIP;',
```

**Comment by Andrewpk** [comment]
I'm sure the extension works fine when accessing DB2 on other systems, but on an iSeries (aka AS/400) the schemas are different. You can still use odbc via PDO.

I can submit a pull request on Monday when I'm back at work with the changes to the code if you'd like to merge them in with yours so that this yii extension supports both DB2 on UNIX/Linux/Windows, etc., and DB2 on an IBM iSeries (as/400) server.

I was able to get things up and running with only having to patch the `$sql` sections of the code today.
I also added a `params` value the extension checks for to know if it needs to use the as/400 style schema, or the schemas you already wrote into the extension.
Setting the `'serverSystem' => 'as400'` in the `params` section now tells my version of the extension to use the iSeries schemas.

I hope you don't mind me submitting the pull request on Monday when I'm back at the office, as I think it would be a valuable asset to the yii community.

**Comment by Andrewpk** [comment]
I started making the necessary changes in order to support the iSeries platform here: https://github.com/Andrewpk/yiidb2

I'll submit a pull request once functionality for the iSeries platform is 100% finished.
